image: ruby:2.5

stages:
  - test
  - deploy

before_script:
- gem install bundler:1.16.6
- bundler update

test:unit:
  stage: test
  script:
    - bundle exec rake full

test:tag:
  stage: test
  only:
    - tags
  script:
    - GEM_RELEASE_VERSION=$CI_COMMIT_TAG ruby test/version.rb

deploy:rubygems:
  stage: deploy
  only: 
    - tags
  script:
    - "echo '---\n:rubygems_api_key: '$RUBYGEMS_API_KEY > ~/.gem/credentials"
    - chmod 0600 ~/.gem/credentials
    - gem build nanocurrency
    - gem push nanocurrency-$CI_COMMIT_TAG.gem
